<a href="https://colab.research.google.com/github/Roberto121c/wizeline_data_engineer_bootcamp/blob/main/week_1/Homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


## Question 1

In [43]:
pd.__version__

'1.5.3'

## Question 2

In [44]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"

# Read the CSV file directly into a DataFrame
df = pd.read_csv(url)

In [45]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [46]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [49]:
df.shape

(20640, 10)

## Question 3

In [50]:
print(df.isnull().sum())

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64


## Question 4

In [69]:
unique_values = df['ocean_proximity'].unique()
print(unique_values)
print(len(unique_values))

['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']
5


## Question 5

In [52]:
#Question 5
df_bay = df.loc[df['ocean_proximity'].isin(['NEAR BAY'])]
print(df_bay['median_house_value'].mean())

259212.31179039303


## Question 6

In [53]:
#Question 6
avg_bedrooms = df['total_bedrooms'].mean()

print(avg_bedrooms)

# Fill the NaN values in column1 using the mean
df['total_bedrooms'].fillna(value=avg_bedrooms, inplace=True)

537.8705525375618


In [54]:
print(df.isnull().sum())
avg_bedrooms = df['total_bedrooms'].mean()

print(avg_bedrooms)

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64
537.8705525375617


## Question 7

In [56]:
#Question 7

#Select all the options located on islands.
df_island = df.loc[df['ocean_proximity'].isin(['ISLAND'])]
df_island.head()


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [59]:
# Select only columns housing_median_age, total_rooms, total_bedrooms.
df_island = df_island[['housing_median_age', 'total_rooms', 'total_bedrooms']]
df_island.head()

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [61]:
# Get the underlying NumPy array.
X = df_island.to_numpy()


# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX
X_T = X.T
XTX = np.dot(X_T, X)
print(XTX)

[[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]


In [62]:
# Compute the inverse of XTX.
XTX_inv = np.linalg.inv(XTX)

print(XTX_inv)

[[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]


In [64]:
# Create an array y with values [950, 1300, 800, 1000, 1300]
y = np.array([950, 1300, 800, 1000, 1300])

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = np.dot(XTX_inv, X_T)
w = np.dot(w, y)

print(w)

[23.12330961 -1.48124183  5.69922946]
